#!/bin/bash
set -e
APP="$1"; PORT="$2";
update_nodes () {
  vars=`echo -e "$1"`

  for word in $vars; do
    KEY=`echo $word | cut -d"=" -f1`
    VALUE=`echo $word | cut -d"=" -f2-`
    domains=`echo $VALUE | tr ',' '\n'`
    for domain in $domains; do
      echo $KEY=$domain
      echo -e `ssh git@$domain dokku nodes:internal:deploy $APP $PORT $KEY`
    done
  done
}

if [[ -d "/home/git/$APP/.git" ]]; then 
  REMOTE_APP="localhost:5000/appl/$APP"
  echo "$REMOTE_APP $APP"
  docker tag app/$APP $REMOTE_APP
  docker push $REMOTE_APP
  update_nodes `cat /home/git/$APP/NODES`
fi